server:
  port: 8086

spring:
  application:
    name: chat-media-service
  datasource:
    url: jdbc:postgresql://localhost:5432/chatapp
    username: chatapp
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.chatapp.mediaservice: DEBUG
    org.springframework.web: DEBUG
