server:
  port: 8091

spring:
  application:
    name: chat-auth-service
  datasource:
    url: jdbc:postgresql://localhost:5440/chatapp
    username: chatapp
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.chatapp.authservice: DEBUG
    org.springframework.web: DEBUG

chatapp:
  app:
    jwtSecret: "fca6b9d3b8be2c2f00ae2857fd8c17efb728dbe82d0668e41f89e54c491b60e8"
    jwtExpirationMs: 3600000
    jwtRefreshExpirationMs: 86400000
    otpExpirationMs: 300000
